// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package foobar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FooBarServiceClient is the client API for FooBarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FooBarServiceClient interface {
	Execute(ctx context.Context, in *Foo, opts ...grpc.CallOption) (*Result, error)
}

type fooBarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFooBarServiceClient(cc grpc.ClientConnInterface) FooBarServiceClient {
	return &fooBarServiceClient{cc}
}

func (c *fooBarServiceClient) Execute(ctx context.Context, in *Foo, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/foobar.FooBarService/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FooBarServiceServer is the server API for FooBarService service.
// All implementations should embed UnimplementedFooBarServiceServer
// for forward compatibility
type FooBarServiceServer interface {
	Execute(context.Context, *Foo) (*Result, error)
}

// UnimplementedFooBarServiceServer should be embedded to have forward compatible implementations.
type UnimplementedFooBarServiceServer struct {
}

func (UnimplementedFooBarServiceServer) Execute(context.Context, *Foo) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}

// UnsafeFooBarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FooBarServiceServer will
// result in compilation errors.
type UnsafeFooBarServiceServer interface {
	mustEmbedUnimplementedFooBarServiceServer()
}

func RegisterFooBarServiceServer(s grpc.ServiceRegistrar, srv FooBarServiceServer) {
	s.RegisterService(&FooBarService_ServiceDesc, srv)
}

func _FooBarService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Foo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooBarServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/foobar.FooBarService/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooBarServiceServer).Execute(ctx, req.(*Foo))
	}
	return interceptor(ctx, in, info, handler)
}

// FooBarService_ServiceDesc is the grpc.ServiceDesc for FooBarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FooBarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "foobar.FooBarService",
	HandlerType: (*FooBarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _FooBarService_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
